version: '3.7'
services:
  mqtt_client:
    build:
      context: .
    restart: always
    env_file:
      - ./.env
   # environment:
    #  - ABASE_URL=${ABASE_URL}
     # - T_SERVER = ${T_SERVER}
     # - T_PORT = ${T_PORT}
     # - T_USER = ${T_USER}
     # - T_PASSWORD = ${T_PASSWORD}